### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ghost**
This PR updates Guzzle to > 7.0.1 and PHPUnit to version 9 (also migrated the configuration). I've done this to be able to use this package in Laravel 8, which requires Guzzle 7.

If you want/need any additional changes, please let me know.

### CODE REVIEW

**Comment by FabianBeiner** [comment]
Thank you so much!

**Comment by vdhicts** [comment]
Thank you for this handy package!

Would you be so kind to tag a new release? That enables the users of this package to use this with regular composer settings (could use dev-master but that requires the minimal stability settings to be changed, prefer to use 1.1.0 for example).

**Comment by FabianBeiner** [comment]
Oh, yeah! Done. :)

**Comment by vdhicts** [comment]
Thank you very much!

**Pull request merged**
